spring:
  application:
    name: dispatcher-servlet-test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: http://localhost:2222/swagger-ui.html

server:
  port: 2222